### ISSUE TITLE
How would I add logic?

### ISSUE THREAD

**Issue by Raj2032** [khonsulabs/kludgine#57]
In the `README.md` page I see a sample code:

```rust
let texture = Texture::load("kludgine/examples/assets/k.png")?;
let sprite = SpriteSource::entire_texture(texture);
sprite.render_at(
    scene,
    Rect::from(scene.size()).center(),
    SpriteRotation::around_center(self.rotation_angle),
);
```

So inside the `sprite.render_at`, how would I add logic, for example if I wanted to add game logic and stuff, commonly `if` statements would be used, so how would I add these kinds of stuff when you are only passing in arguments to a function?

**Comment by ecton** [comment]
Sorry for the delay in responding. The [kludgine/examples](https://github.com/khonsulabs/kludgine/tree/main/kludgine/examples) folder has full examples that demonstrate how to build a program with Kludgine.

The general design of Kludgine is that the update() function fires, and then the render() function fires (if needed). Most examples are fairly simple, but the [`orthotiles`](https://github.com/khonsulabs/kludgine/blob/main/kludgine/examples/orthotiles.rs) example shows basic arrow-key driven movement. (`cargo run --example orthotiles --features app,unstable-apis`)

This project is a little under-developed at the moment, but I have been keeping it up-to-date with the latest wgpu releases.

**Comment by Raj2032** [comment]
@ecton Hey man thanks for your help :)

**Comment by ecton** [comment]
@Raj2032 My pleasure. I think this library is stable and works well, it just doesn't have a lot of features. I'm happy to answer any questions or look into fixing/improving anything you have feedback on!

**Comment by Raj2032** [comment]
@ecton :)

As a matter of fact I do have a quesiton/suggestion. From what I can see the game engine is a framework based library, something similar to 3g3d and bevy. My suggestion is that it shouldn't have a locked in framework when coding. Personally with me its easier and better to code without some locked in framework.

Take a look at [macroquad](https://github.com/not-fl3/macroquad) it doesn't lock you into some kind of framework.

Just my opinion and I am not trying to criticize your project, I think it looks fairly easy so good job on that mate :)

**Comment by ecton** [comment]
@Raj2032 Good feedback. Kludgine goes a little beyond what macroquad does by supporting multiple windows. That's where the current design came from -- `SingleWindowApplication` just simplifies running an application that doesn't need multiple windows.

You're right, however, that even `SingleWindowApplication` is overkill for simple apps. I've opened up a new issue to come up with an even simpler interface.

**Comment by Raj2032** [comment]
@ecton Hi thanks for taking my consideration :)

So its quite interesting actually that your game engine supports multiple windows.

So if you do come up with a simplier solution, would this apply to multiwindow application support as well? And is this going to be locked in framework or is it going to be more like where you can code freely? Just curious to know mate :)
