### ISSUE TITLE
Errors when attempting to compile examples

### ISSUE THREAD

**Issue by rspeir** [khonsulabs/kludgine#69]
When I try to run the basic.rs example, I receive a compile error:

```
cargo run --example basic

error[E0432]: unresolved import `ahash::AHashMap`
  --> src\lib.rs:16:13
   |
16 | use ahash::{AHashMap, AHasher};
   |             ^^^^^^^^ no `AHashMap` in the root
```

I was able to resolve this by changing the default-features flag of the ahash crate to true instead of false in Cargo.toml (line 27):
```
ahash = { version = "0.8.3", default-features = true }
```

I'm still very new to Rust, so I have no idea if this will have undesired effects down the line, but it seemed to allow the basic.rs example to compile and run.

**Comment by ecton** [comment]
So interesting that I'm not having that issue! I can't remember why I disabled the default features, so I'll re-enable them.
